### ISSUE TITLE
Cannot build PDB profile - no valid cabinets found

### ISSUE THREAD

**Issue by madsumm** [google/rekall#189]
Hi,
Was trying to custom build profile using version_scan, fetch_pdb & parse_pdb.
At the fetch_pdb stage, I have the following errors:

```
$ rekal fetch_pdb ntkrnlmp.pdb 6E60B4B61FB04E34A3688B615F16020A1
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/6E60B4B61FB04E34A3688B615F16020A1/ntkrnlmp.pd_
/tmp/tmpiyt6wD/ntkrnlmp.pd_: no valid cabinets found                                                                     

All done, errors in processing 1 file(s)
2016-10-05 01:53:25,284:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 860, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/tools/mspdb.py", line 152, in render
    pdb_file_data = self.FetchPDBFile()
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/tools/mspdb.py", line 211, in FetchPDBFile
    "Ensure cabextract is installed.\n" % output_file)
RuntimeError: Failed to decompress output file /tmp/tmpiyt6wD/ntkrnlmp.pdb. Ensure cabextract is installed.


2016-10-05 01:53:25,285:CRITICAL:root:Failed to decompress output file /tmp/tmpiyt6wD/ntkrnlmp.pdb. Ensure cabextract is installed.
. Try --debug for more information.
Traceback (most recent call last):
  File "/usr/local/bin/rekal", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/rekall/rekal.py", line 99, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 863, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 860, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/tools/mspdb.py", line 152, in render
    pdb_file_data = self.FetchPDBFile()
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/tools/mspdb.py", line 211, in FetchPDBFile
    "Ensure cabextract is installed.\n" % output_file)
RuntimeError: Failed to decompress output file /tmp/tmpiyt6wD/ntkrnlmp.pdb. Ensure cabextract is installed.
```

It looks like msdl.microsoft.com is no longer available or missing.
I tried on various memory images and with the same results.
Rgds
Mathew

**Comment by scudette** [comment]
Thanks for this report - it seems that Microsoft suddenly broke their symbol server. The server response seems to be:

```
<html><head><title>Microsoft Corporation</title><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7"></meta><meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta><meta name="SearchTitle" content="Microsoft.com" scheme=""></meta><meta name="Description" content="Get product information, support, and news from Microsoft." scheme=""></meta><meta name="Title" content="Microsoft.com Home Page" scheme=""></meta><meta name="Keywords" content="Microsoft, product, support, help, training, Office, Windows, software, download, trial, preview, demo,  business, security, update, free, computer, PC, server, search, download, install, news" scheme=""></meta><meta name="SearchDescription" content="Microsoft.com Homepage" scheme=""></meta></head><body><p>Your current User-Agent string appears to be from an automated process, if this is incorrect, please click this link:<a href="http://www.microsoft.com/en/us/default.aspx?redir=true">United States English Microsoft Homepage</a></p></body></html>\r\n
```

According to 
https://msdn.microsoft.com/en-us/library/windows/desktop/ee416588(v=vs.85).aspx

This is still supposed to work so maybe its a Microsoft outage? I will investigate further.

**Comment by scudette** [comment]
Ok I figured it out by comparing the HTTP traffic from the official symchk.exe with the symbol server. It seems that MS require a later version in the useragent string.

This should be fixed in 131d7555d5a02dc57f15be4bf852864421d78948 now. Thanks for reporting.

**Comment by madsumm** [comment]
No prob, will test it out shortly

**Comment by raviteja7** [comment]
I tested it, but still receiving the same error.

The GUID is 036C69F689E242E8B76E4D453901D6EC2

![image](https://cloud.githubusercontent.com/assets/2549509/19276536/af7d1a88-8fa4-11e6-9077-711e510741f1.png)

![image](https://cloud.githubusercontent.com/assets/2549509/19276655/1aa07f6c-8fa5-11e6-8abf-5a4e358415ce.png)

Thanks

**Comment by raviteja7** [comment]
I did not have cabextract installed on my box. After installing it, it went smoothly.
![image](https://cloud.githubusercontent.com/assets/2549509/19277806/064faa70-8fa9-11e6-8fd4-f1e0565f457d.png)

![image](https://cloud.githubusercontent.com/assets/2549509/19277815/1153d3ba-8fa9-11e6-828b-42aac527bce0.png)

Thanks

**Comment by Dr4s1l** [comment]
Actually I still got error on the pdb file fetching : 

```
2016-10-14 10:03:29,431:ERROR:rekall.1:Error: HTTP Error 503: Service Unavailable
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrnlpa.pdb/D372A6779D6643FAB5F8CA3D0C2E2CB01/ntkrnlpa.pd_
/tmp/tmpJvI9yB/ntkrnlpa.pd_: no valid cabinets found                                                                     

All done, errors in processing 1 file(s)
/tmp/tmpTRlshi/ntoskrnl.pd_: no valid cabinets found

All done, errors in processing 1 file(s)
```

**Comment by madsumm** [comment]
It worked. Thanks!
