### ISSUE TITLE
Shimcachemem Provides no results for 2012 Server

### ISSUE THREAD

**Issue by dsweet04** [google/rekall#203]
When running the shimcachemem plugin against 2012 server, no results are found.

Results from `rekal.exe -v --live - shimcachemem`

```
2016-10-18 13:58:21,486:DEBUG:rekall.1:Using PMEM driver at \\.\pmem
2016-10-18 13:58:21,487:DEBUG:rekall.1:Logging level set to 10
2016-10-18 13:58:21,489:DEBUG:rekall.1:Using PMEM driver at \\.\pmem
2016-10-18 13:58:21,489:DEBUG:rekall.1:Will detect profile using these Detectors: linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux
2016-10-18 13:58:22,720:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/inventory.gz
2016-10-18 13:58:22,776:DEBUG:rekall.1:Opened local file C:\Users\DS\.rekall_cache\v1.0\inventory.gz
2016-10-18 13:58:22,818:DEBUG:rekall.1:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz
2016-10-18 13:58:22,880:DEBUG:rekall.1:Opened local file C:\Users\DS\.rekall_cache\v1.0\inventory.gz
2016-10-18 13:58:22,880:DEBUG:rekall.1:Opened local file C:\Users\DS\.rekall_cache\v1.0\Linux\index.gz
2016-10-18 13:58:22,921:INFO:rekall.1:Loaded profile Linux/index from Local Cache Directory:C:\Users\DS\.rekall_cache (in 0.0419998168945 sec)
2016-10-18 13:58:22,923:DEBUG:rekall.1:Opened local file C:\Users\DS\.rekall_cache\v1.0\nt\eprocess_index.gz
2016-10-18 13:58:22,947:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:C:\Users\DS\.rekall_cache (in 0.0260000228882 sec)
2016-10-18 13:58:22,948:DEBUG:rekall.1:Opened local file C:\Users\DS\.rekall_cache\v1.0\nt\index.gz
2016-10-18 13:58:22,979:INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:C:\Users\DS\.rekall_cache (in 0.0300002098083 sec)
2016-10-18 13:58:22,980:DEBUG:rekall.1:Opened local file C:\Users\DS\.rekall_cache\v1.0\OSX\index.gz
2016-10-18 13:58:22,980:INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:C:\Users\DS\.rekall_cache (in 0.0 sec)
2016-10-18 13:58:22,980:DEBUG:rekall.1:Opened local file C:\Users\DS\.rekall_cache\v1.0\pe.gz
2016-10-18 13:58:22,990:INFO:rekall.1:Loaded profile pe from Local Cache Directory:C:\Users\DS\.rekall_cache (in 0.00999999046326 sec)
2016-10-18 13:58:22,990:DEBUG:rekall.1:Trying method pe, offset 0
2016-10-18 13:58:22,992:DEBUG:rekall.1:Trying method windows_kernel_file, offset 0
2016-10-18 13:58:23,020:DEBUG:root:Loaded configuration from C:\Users\DS\.rekallrc
2016-10-18 13:58:23,023:DEBUG:rekall.2:Logging level set to 30
2016-10-18 13:58:23,026:DEBUG:rekall.1:Opened local file C:\Users\DS\.rekall_cache\v1.0\ntfs.gz
2016-10-18 13:58:23,115:INFO:rekall.1:Found RSDS in kernel image: A9BBA3C139724A738BE17665DB4393CA1 (ntkrnlmp.pdb)
2016-10-18 13:58:23,117:DEBUG:rekall.1:Opened local file C:\Users\DS\.rekall_cache\v1.0\nt\GUID\A9BBA3C139724A738BE17665DB4393CA1.gz
2016-10-18 13:58:23,410:INFO:rekall.1:Loaded profile nt/GUID/A9BBA3C139724A738BE17665DB4393CA1 from Local Cache Directory:C:\Users\DS\.rekall_cache (in 0.292999982834 sec)
2016-10-18 13:58:23,428:INFO:rekall.1:Detected ntkrnlmp.pdb with GUID A9BBA3C139724A738BE17665DB4393CA1
2016-10-18 13:58:23,428:INFO:rekall.1:Detection method windows_kernel_file yielded profile <AMD64 profile nt/GUID/A9BBA3C139724A738BE17665DB4393CA1 (Nt)>
2016-10-18 13:58:23,430:DEBUG:rekall.1:Running plugin (shimcachemem) with args (()) kwargs ({'profile': None})
2016-10-18 13:58:23,464:DEBUG:rekall.1:Switching to Kernel context
2016-10-18 13:58:24,927:DEBUG:rekall.1:Switching to Kernel context
2016-10-18 13:58:24,928:DEBUG:rekall.1:Switching to Kernel context
2016-10-18 13:58:25,095:DEBUG:rekall.1:Switching to Kernel context
2016-10-18 13:58:25,661:DEBUG:rekall.1:Skipped profile ahcache/GUID/EA55742C16EB4423805C3E2BA6BC88C01 from https://github.com/google/rekall-profiles/raw/master (Not in inventory)
2016-10-18 13:58:25,661:DEBUG:rekall.1:Skipped profile ahcache/GUID/EA55742C16EB4423805C3E2BA6BC88C01 from http://profiles.rekall-forensic.com (Not in inventory)
2016-10-18 13:58:25,661:DEBUG:rekall.1:Will build local profile ahcache/GUID/EA55742C16EB4423805C3E2BA6BC88C01
Microsoft (R) File Expansion Utility  Version 6.3.9600.16384
Copyright (c) Microsoft Corporation. All rights reserved.

Copying c:\users\ds\appdata\local\temp\tmpeybahh\ahcache.pd_ to c:\users\ds\appdata\local\temp\tmpeybahh\ahcache.pdb.
c:\users\ds\appdata\local\temp\tmpeybahh\ahcache.pd_: 1020 bytes copied.

2016-10-18 13:58:26,036:DEBUG:rekall.1:Opened local file C:\Users\DS\.rekall_cache\v1.0\mspdb.gz
2016-10-18 13:58:26,042:INFO:rekall.1:Loaded profile mspdb from Local Cache Directory:C:\Users\DS\.rekall_cache (in 0.00500011444092 sec)
2016-10-18 13:58:26,042:DEBUG:rekall.1:Building profile from PE Exports for ahcache
2016-10-18 13:58:26,063:DEBUG:rekall.1:Listed 44 processes using PsActiveProcessHead
2016-10-18 13:58:26,540:DEBUG:rekall.1:Listed 40 processes using CSRSS
2016-10-18 13:58:27,065:DEBUG:rekall.1:Listed 44 processes using PspCidTable
2016-10-18 13:58:27,082:DEBUG:rekall.1:Listed 42 processes using Sessions
2016-10-18 13:58:27,115:DEBUG:rekall.1:Listed 42 processes using Handles
     Shim              Last Modified          File Size  Path
-------------- ------------------------------ ---------- ----
```

**Comment by scudette** [comment]
This looks to me like it is the same problem with the MS symbol server not accepting an old user agent string. This is unexpectedly short:
```
c:\users\ds\appdata\local\temp\tmpeybahh\ahcache.pd_: 1020 bytes copied.
```

Did you try this with Rekall head?

**Comment by dsweet04** [comment]
If I add --autodetect_build_local none as a flag and run this plugin against Windows 7, 8.1, and 2008 Server they all work no problem without reaching out. It's only 2012 Server that I'm getting this issue from.

**Comment by scudette** [comment]
This makes sense. The fix for the user agent was only committed recently.  This should be fixed in the next release, currently scheduled for next week.

**Comment by dsweet04** [comment]
Still not getting shimcahcemem to work on windows 2012 server.

```
C:\Program Files\Rekall>rekal.exe --live Memory -v - shimcachemem
2016-11-09 12:04:18,558:DEBUG:rekall.1:Unable to open \\.\pmem: (2, 'CreateFile'
, 'The system cannot find the file specified.')
2016-11-09 12:04:18,562:DEBUG:rekall.1:Loading driver from C:\PROGRA~1\Rekall\re
sources\WinPmem/winpmem_x64.sys
2016-11-09 12:04:18,562:DEBUG:rekall.1:Removing service pmem
2016-11-09 12:04:18,563:DEBUG:rekall.1:pmem service does not exist.
2016-11-09 12:04:18,565:DEBUG:rekall.1:Created service pmem
2016-11-09 12:04:18,601:DEBUG:rekall.1:Logging level set to 10
2016-11-09 12:04:18,601:DEBUG:rekall.1:Will detect profile using these Detectors
: linux_index,nt_index,tsk,osx,pe,windows_kernel_file,rsds,ntfs,linux
2016-11-09 12:04:19,611:WARNING:rekall.1:Inventory for repository "https://githu
b.com/google/rekall-profiles/raw/master" seems malformed. Are you behind a capti
ve portal or proxy? If this is a custom repository, did you forget to create an
inventory? You must use the tools/profiles/build_profile_repo.py tool with the -
-inventory flag.
2016-11-09 12:04:19,611:WARNING:rekall.1:Repository https://github.com/google/re
kall-profiles/raw/master will be disabled.
2016-11-09 12:04:19,614:WARNING:rekall.1:Inventory for repository "http://profil
es.rekall-forensic.com" seems malformed. Are you behind a captive portal or prox
y? If this is a custom repository, did you forget to create an inventory? You mu
st use the tools/profiles/build_profile_repo.py tool with the --inventory flag.
2016-11-09 12:04:19,615:WARNING:rekall.1:Repository http://profiles.rekall-foren
sic.com will be disabled.
2016-11-09 12:04:19,615:WARNING:rekall.1:No usable repositories were found. Reka
ll Will attempt to use the local cache. This is likely to fail if profiles are m
issing locally!
2016-11-09 12:04:19,617:DEBUG:rekall.1:Opened local file C:\Users\DS\.rekall_cac
he\v1.0\inventory.gz
2016-11-09 12:04:19,618:DEBUG:rekall.1:Opened local file C:\Users\DS\.rekall_cac
he\v1.0\Linux\index.gz
2016-11-09 12:04:19,625:INFO:rekall.1:Loaded profile Linux/index from Directory:
C:\Users\DS\.rekall_cache (in 0.00799989700317 sec)
2016-11-09 12:04:19,627:DEBUG:rekall.1:Opened local file C:\Users\DS\.rekall_cac
he\v1.0\nt\eprocess_index.gz
2016-11-09 12:04:19,654:INFO:rekall.1:Loaded profile nt/eprocess_index from Dire
ctory:C:\Users\DS\.rekall_cache (in 0.0269999504089 sec)
2016-11-09 12:04:19,654:DEBUG:rekall.1:Opened local file C:\Users\DS\.rekall_cac
he\v1.0\nt\index.gz
2016-11-09 12:04:19,743:INFO:rekall.1:Loaded profile nt/index from Directory:C:\
Users\DS\.rekall_cache (in 0.0880000591278 sec)
2016-11-09 12:04:19,744:DEBUG:rekall.1:Opened local file C:\Users\DS\.rekall_cac
he\v1.0\OSX\index.gz
2016-11-09 12:04:19,744:INFO:rekall.1:Loaded profile OSX/index from Directory:C:
\Users\DS\.rekall_cache (in 0.000999927520752 sec)
2016-11-09 12:04:19,746:DEBUG:rekall.1:Opened local file C:\Users\DS\.rekall_cac
he\v1.0\pe.gz
2016-11-09 12:04:19,755:INFO:rekall.1:Loaded profile pe from Directory:C:\Users\
DS\.rekall_cache (in 0.0090000629425 sec)
2016-11-09 12:04:19,756:DEBUG:rekall.1:Trying method pe, offset 0
2016-11-09 12:04:19,757:DEBUG:rekall.1:Trying method windows_kernel_file, offset
 0
2016-11-09 12:04:19,767:INFO:rekall.1:Found RSDS in kernel image: A9BBA3C139724A
738BE17665DB4393CA1 (ntkrnlmp.pdb)
2016-11-09 12:04:19,769:DEBUG:rekall.1:Opened local file C:\Users\DS\.rekall_cac
he\v1.0\nt\GUID\A9BBA3C139724A738BE17665DB4393CA1.gz
2016-11-09 12:04:20,075:INFO:rekall.1:Loaded profile nt/GUID/A9BBA3C139724A738BE
17665DB4393CA1 from Directory:C:\Users\DS\.rekall_cache (in 0.305999994278 sec)
2016-11-09 12:04:20,098:INFO:rekall.1:Detected ntkrnlmp.pdb with GUID A9BBA3C139
724A738BE17665DB4393CA1
2016-11-09 12:04:20,098:INFO:rekall.1:Detection method windows_kernel_file yield
ed profile <AMD64 profile nt/GUID/A9BBA3C139724A738BE17665DB4393CA1 (Nt)>
2016-11-09 12:04:20,099:DEBUG:rekall.1:Running plugin (shimcachemem) with args (
()) kwargs ({'profile': None, 'verbosity': 1})
     Shim                 last_mod               size    Path
-------------- ------------------------------ ---------- ----
2016-11-09 12:04:20,138:DEBUG:rekall.1:Switching to Kernel context
2016-11-09 12:04:21,486:DEBUG:rekall.1:Switching to Kernel context
2016-11-09 12:04:21,489:DEBUG:rekall.1:Switching to Kernel context
2016-11-09 12:04:21,648:DEBUG:rekall.1:Switching to Kernel context
2016-11-09 12:04:22,233:DEBUG:rekall.1:Opened local file C:\Users\DS\.rekall_cac
he\v1.0\ahcache\GUID\EA55742C16EB4423805C3E2BA6BC88C01.gz
2016-11-09 12:04:22,237:INFO:rekall.1:Loaded profile ahcache/GUID/EA55742C16EB44
23805C3E2BA6BC88C01 from Directory:C:\Users\DS\.rekall_cache (in 0.0049998760223
4 sec)
2016-11-09 12:04:22,260:DEBUG:rekall.1:Listed 42 processes using PsActiveProcess
Head
2016-11-09 12:04:22,585:DEBUG:rekall.1:Listed 38 processes using CSRSS
2016-11-09 12:04:23,131:DEBUG:rekall.1:Listed 42 processes using PspCidTable
2016-11-09 12:04:23,148:DEBUG:rekall.1:Listed 40 processes using Sessions
2016-11-09 12:04:23,181:DEBUG:rekall.1:Listed 41 processes using Handles
0xc000003ffa58 -                              -
2016-11-09 12:04:23,507:DEBUG:rekall.1:Removing service pmem
2016-11-09 12:04:23,509:DEBUG:rekall.1:Stopping service: pmem
2016-11-09 12:04:23,517:DEBUG:rekall.1:Deleting service: pmem

C:\Program Files\Rekall>
```

**Comment by scudette** [comment]
Hmm I verified that it does not work on 2012 server. I initially just implemented the research published in the paper https://www.fireeye.com/blog/threat-research/2015/10/shim_shady_live_inv/shim-shady-part-2.html but it looks like this version is not properly reversed.

I will look into it some more and see if I can figure out how to extract the constants.
